plugins:
  - jekyll-relative-links
remote_theme: minima
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - ML.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - PRIVACY_NOTICE.md
